package pl.luznykolo.prestigioweather;
import android.app.*;import android.os.*;import android.view.*;import android.graphics.*;import android.graphics.drawable.*;import org.json.*;import java.io.*;import java.net.*;import java.text.*;import java.util.*;import javax.net.ssl.*;import java.security.*;import java.security.cert.Certificate;import java.security.cert.CertificateFactory;import org.conscrypt.Conscrypt;

public class MainActivity extends Activity{
 WeatherView v; Handler h=new Handler();
 final String URLS="https://api.open-meteo.com/v1/forecast?latitude=51.1136&longitude=20.8716&current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m,surface_pressure,visibility&hourly=temperature_2m,precipitation_probability,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset&timezone=Europe%2FWarsaw&forecast_days=6";
 public void onCreate(Bundle b){super.onCreate(b);try{Security.insertProviderAt(Conscrypt.newProvider(),1);}catch(Throwable e){}getWindow().addFlags(128);hide();v=new WeatherView();setContentView(v);tick.run();refresh.run();}
 Runnable tick=new Runnable(){public void run(){v.invalidate();h.postDelayed(this,1000);}};
 Runnable refresh=new Runnable(){public void run(){fetch();h.postDelayed(this,900000);}};
 void fetch(){new Thread(new Runnable(){public void run(){try{String x=get(URLS);getPreferences(0).edit().putString("cache",x).apply();show(x,true);}catch(Exception e){String c=getPreferences(0).getString("cache",null);if(c!=null)show(c,false);else{v.status="Błąd połączenia";v.invalidate();}}}}).start();}
 String get(String u)throws Exception{CertificateFactory cf=CertificateFactory.getInstance("X.509");InputStream in=getResources().openRawResource(R.raw.isrgrootx1);Certificate ca;try{ca=cf.generateCertificate(in);}finally{in.close();}KeyStore ks=KeyStore.getInstance(KeyStore.getDefaultType());ks.load(null,null);ks.setCertificateEntry("isrg-root-x1",ca);TrustManagerFactory tmf=TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());tmf.init(ks);SSLContext sc=SSLContext.getInstance("TLS");sc.init(null,tmf.getTrustManagers(),null);HttpsURLConnection c=(HttpsURLConnection)new URL(u).openConnection();c.setSSLSocketFactory(sc.getSocketFactory());c.setConnectTimeout(20000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/json");c.setRequestProperty("User-Agent","PrestigioWeather/12");BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),"UTF-8"));StringBuilder b=new StringBuilder();String z;while((z=r.readLine())!=null)b.append(z);r.close();return b.toString();}
 void show(final String raw,final boolean online){runOnUiThread(new Runnable(){public void run(){try{v.setData(new JSONObject(raw));v.status=online?"Ostatnia aktualizacja: "+new SimpleDateFormat("dd.MM.yyyy HH:mm").format(new Date()):"Offline — ostatnie dane";v.invalidate();}catch(Exception e){v.status="Błąd danych";}}});}
 int rnd(double x){return(int)Math.round(x);}String hm(String s){return s.length()>=16?s.substring(11,16):"--:--";}
 String wt(int c){if(c==0)return"Bezchmurnie";if(c<=2)return"Częściowe zachmurzenie";if(c==3)return"Pochmurno";if(c==45||c==48)return"Mgła";if(c>=51&&c<=57)return"Mżawka";if(c>=61&&c<=67)return"Deszcz";if(c>=71&&c<=77)return"Śnieg";if(c>=80&&c<=82)return"Przelotny deszcz";if(c>=95)return"Burza";return"Pogoda";}
 int icon(int c){if(c==0)return R.drawable.ic_sun;if(c<=2)return R.drawable.ic_partly;if(c==3||c==45||c==48)return R.drawable.ic_cloud;if((c>=51&&c<=67)||(c>=80&&c<=82))return R.drawable.ic_rain;if(c>=71&&c<=77)return R.drawable.ic_snow;return R.drawable.ic_cloud;}
 class WeatherView extends View{
  Bitmap bg; Paint p=new Paint(3); JSONObject data; String status="Łączenie…"; Rect src=new Rect();
  WeatherView(){super(MainActivity.this);bg=BitmapFactory.decodeResource(getResources(),R.drawable.dashboard_reference);}
  void setData(JSONObject j){data=j;}
  void txt(Canvas c,String s,float x,float y,float size,boolean bold,int color){p.setColor(color);p.setTextSize(size);p.setTypeface(bold?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);p.setTextAlign(Paint.Align.LEFT);p.setStyle(Paint.Style.FILL);c.drawText(s,x,y,p);}
  void center(Canvas c,String s,float x,float y,float size,boolean bold,int color){p.setColor(color);p.setTextSize(size);p.setTypeface(bold?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);p.setTextAlign(Paint.Align.CENTER);p.setStyle(Paint.Style.FILL);c.drawText(s,x,y,p);}
  void glass(Canvas c,float l,float t,float r,float b,float rad){p.setColor(Color.argb(220,2,37,65));p.setStyle(Paint.Style.FILL);c.drawRoundRect(l,t,r,b,rad,rad,p);p.setColor(Color.rgb(31,174,232));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.2f);c.drawRoundRect(l,t,r,b,rad,rad,p);p.setStyle(Paint.Style.FILL);}
  Bitmap bm(int id){return BitmapFactory.decodeResource(getResources(),id);}
  protected void onDraw(Canvas c){super.onDraw(c);float sx=getWidth()/1024f,sy=getHeight()/600f;c.save();c.scale(sx,sy);src.set(0,0,bg.getWidth(),bg.getHeight());c.drawBitmap(bg,src,new Rect(0,0,1024,600),p);
   // repaint every dynamic region over the reference, preserving the exact approved visual language
   glass(c,28,72,492,224,15); glass(c,505,82,735,224,15); glass(c,748,35,994,276,15); glass(c,28,320,505,522,15); glass(c,520,320,994,522,15);
   Date now=new Date();txt(c,new SimpleDateFormat("HH:mm").format(now),48,166,92,true,Color.WHITE);txt(c,new SimpleDateFormat("EEEE, d MMMM yyyy",new Locale("pl","PL")).format(now),48,207,19,true,Color.WHITE);
   txt(c,"SKARŻYSKO-KAMIENNA",786,66,17,true,Color.WHITE);txt(c,"51.1136° N, 20.8716° E",786,88,12,false,Color.WHITE);
   if(data!=null)try{JSONObject q=data.getJSONObject("current"),d=data.getJSONObject("daily"),ho=data.getJSONObject("hourly");int code=q.getInt("weather_code");Bitmap ic=bm(icon(code));c.drawBitmap(ic,null,new Rect(520,94,615,189),p);txt(c,rnd(q.getDouble("temperature_2m"))+"°C",616,161,58,true,Color.WHITE);txt(c,wt(code),616,196,17,true,Color.WHITE);
    String[] lab={"Odczuwalna","Wilgotność","Wiatr","Ciśnienie","Widoczność"};String[] val={rnd(q.getDouble("apparent_temperature"))+"°C",rnd(q.getDouble("relative_humidity_2m"))+"%",rnd(q.getDouble("wind_speed_10m"))+" km/h",rnd(q.optDouble("surface_pressure",0))+" hPa",String.format(Locale.US,"%.0f km",q.optDouble("visibility",0)/1000.0)};int[] cols={0xffff594d,0xff21c7ff,0xff20e5aa,0xffffb400,0xffa86cff};for(int i=0;i<5;i++){p.setColor(cols[i]);c.drawCircle(770,119+i*35,8,p);txt(c,lab[i],790,125+i*35,15,false,Color.WHITE);p.setTextAlign(Paint.Align.RIGHT);txt(c,val[i],900,125+i*35,16,true,Color.WHITE);}
    txt(c,"Prognoza godzinowa",48,350,19,true,Color.WHITE);txt(c,"Prognoza na 5 dni",540,350,19,true,Color.WHITE);p.setColor(0xff58d8ff);c.drawRect(48,362,485,363,p);c.drawRect(540,362,975,363,p);
    JSONArray ht=ho.getJSONArray("time"),hT=ho.getJSONArray("temperature_2m"),hc=ho.getJSONArray("weather_code"),pr=ho.getJSONArray("precipitation_probability");String n=new SimpleDateFormat("yyyy-MM-dd'T'HH:00").format(now);int st=0;for(int i=0;i<ht.length();i++)if(ht.getString(i).compareTo(n)>=0){st=i;break;}for(int k=0;k<6;k++){int z=st+k;float x=70+k*72;center(c,hm(ht.getString(z)),x,388,13,false,Color.WHITE);Bitmap bi=bm(icon(hc.getInt(z)));c.drawBitmap(bi,null,new Rect((int)x-25,397,(int)x+25,447),p);center(c,rnd(hT.getDouble(z))+"°",x,474,18,true,Color.WHITE);center(c,"● "+pr.optInt(z,0)+"%",x,502,13,true,0xff26cfff);}
    JSONArray dt=d.getJSONArray("time"),mx=d.getJSONArray("temperature_2m_max"),mn=d.getJSONArray("temperature_2m_min"),dc=d.getJSONArray("weather_code"),pp=d.getJSONArray("precipitation_probability_max");SimpleDateFormat inf=new SimpleDateFormat("yyyy-MM-dd",Locale.US),dn=new SimpleDateFormat("EEE",new Locale("pl","PL")),dd=new SimpleDateFormat("dd.MM");for(int k=1;k<=5;k++){float x=560+(k-1)*86;Date day=inf.parse(dt.getString(k));center(c,dn.format(day),x,387,14,true,Color.WHITE);center(c,dd.format(day),x,405,11,false,Color.WHITE);Bitmap bi=bm(icon(dc.getInt(k)));c.drawBitmap(bi,null,new Rect((int)x-25,410,(int)x+25,460),p);center(c,rnd(mx.getDouble(k))+"°",x,482,18,true,Color.WHITE);center(c,rnd(mn.getDouble(k))+"°",x,500,13,false,0xff73c9ff);center(c,"● "+pp.optInt(k,0)+"%",x,517,12,true,0xff26cfff);}
   }catch(Exception e){}
   // footer is always repainted
   p.setColor(Color.argb(180,0,0,0));c.drawRect(0,548,1024,600,p);txt(c,"Stacja Pogodowa",25,580,14,false,Color.WHITE);p.setTextAlign(Paint.Align.RIGHT);txt(c,status,760,580,12,false,Color.WHITE);
   c.restore();}
 }
 void hide(){getWindow().getDecorView().setSystemUiVisibility(5894|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}public void onWindowFocusChanged(boolean f){super.onWindowFocusChanged(f);if(f)hide();}public void onBackPressed(){}
}
